version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - despenser08

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - despenser08

